org: benmusch
app: letterboxd-slack
service: aws-python-scheduled-cron

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.8

functions:
  cron:
    handler: letterboxd_slack.main
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
