org: benmusch
app: letterboxd-slack
service: letterboxd-slack-cron

frameworkVersion: ">=2.0.0 <3.0.0"

provider:
  name: aws
  runtime: python3.8
  profile: serverless

functions:
  cron:
    handler: letterboxd_slack.main
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
